# justfile

set shell := ["bash", "-cu"]

MANAGER := "npm"

pre_example:
    echo "pre_example"

example: pre_example
    echo {{MANAGER}}

run *args:
    {{MANAGER}} {{args}}

cmd +args='':
    #!/usr/bin/env bash

    # args를 배열로 파싱
    # 공백 기준으로 잘라 ARGS라는 배열에 담음
    read -ra ARGS <<< "{{args}}"

    cmd="${ARGS[0]}"

    case "$cmd" in
      example)
        just example
        ;;
      *)
        just run {{args}}
        ;;
    esac
