# justfile

set shell := ["bash", "-cu"]

MANAGER := "npm"

pre_example:
    echo "pre_example"

example: pre_example
    echo {{MANAGER}}

run *args:
    {{MANAGER}} {{args}}

cmd +args='':
    #!/usr/bin/env bash

    # args를 배열로 파싱
    # 공백 기준으로 잘라 ARGS라는 배열에 담음
    read -ra ARGS <<< "{{args}}"

    # 첫 번째 인자를 subcmd로
    subcmd="${ARGS[0]}"

    # 첫 번째 인자를 제거한 나머지를 ARGS로 다시 할당
    ARGS=("${ARGS[@]:1}")

    case "$subcmd" in
      example)
        just example
        ;;
      *)
        # 첫 인자가 dev|storybook|deploy가 아닐 경우,
        # (첫 인자 + 나머지 인자들)을 전부 just run으로 전달
        just run "$subcmd" "${ARGS[@]}"
        ;;
    esac
