set quiet
set positional-arguments

[no-exit-message]
_run *args:
  {{MANAGER}} {{args}}

[no-exit-message]
_cmd +args='':
  #!/usr/bin/env bash
  # 1) 원하는 커맨드를 공백으로 구분해 저장
  USER_COMMAND="$(just --summary)"
  # 2) USER_COMMAND를 case에 맞는 패턴으로 변환
  PATTERN=$(echo "$USER_COMMAND" | sed 's/ /|/g')

  case "$1" in
    ls)
      just --list --list-prefix '' --list-heading '' --unsorted
      ;;
    $PATTERN)
      just "$1"
      ;;
    *)
      just _run {{args}}
      ;;
  esac
